export const POPULAR_CITIES = [
  "Mumbai, India",
  "New Delhi, India",
  "Bengaluru, India",
  "Goa, India",
  "Jaipur, India",
  "Udaipur, India",
  "Kolkata, India",
  "Chennai, India",
  "Kochi, India",
  "Manali, India",
  "Leh, India",
  "Rishikesh, India",
  "Srinagar, India",
  "Shimla, India",
  "Darjeeling, India",
  "Andaman Islands, India",
  "Tokyo, Japan",
  "Kyoto, Japan",
  "Osaka, Japan",
  "Seoul, South Korea",
  "Bangkok, Thailand",
  "Phuket, Thailand",
  "Chiang Mai, Thailand",
  "Bali, Indonesia",
  "Singapore",
  "Kuala Lumpur, Malaysia",
  "Hong Kong",
  "Dubai, UAE",
  "Abu Dhabi, UAE",
  "Istanbul, Türkiye",
  "Cairo, Egypt",
  "Cape Town, South Africa",
  "Nairobi, Kenya",
  "London, UK",
  "Edinburgh, UK",
  "Paris, France",
  "Nice, France",
  "Rome, Italy",
  "Florence, Italy",
  "Venice, Italy",
  "Barcelona, Spain",
  "Madrid, Spain",
  "Lisbon, Portugal",
  "Amsterdam, Netherlands",
  "Berlin, Germany",
  "Munich, Germany",
  "Prague, Czechia",
  "Vienna, Austria",
  "Zurich, Switzerland",
  "Interlaken, Switzerland",
  "Santorini, Greece",
  "Athens, Greece",
  "Reykjavík, Iceland",
  "Oslo, Norway",
  "Stockholm, Sweden",
  "Copenhagen, Denmark",
  "New York, USA",
  "San Francisco, USA",
  "Los Angeles, USA",
  "Las Vegas, USA",
  "Miami, USA",
  "Chicago, USA",
  "Honolulu, USA",
  "Toronto, Canada",
  "Vancouver, Canada",
  "Mexico City, Mexico",
  "Cancún, Mexico",
  "Rio de Janeiro, Brazil",
  "Buenos Aires, Argentina",
  "Lima, Peru",
  "Sydney, Australia",
  "Melbourne, Australia",
  "Auckland, New Zealand",
  "Queenstown, New Zealand",
];

export const INTEREST_OPTIONS = [
  { label: "Food", emoji: "🍜" },
  { label: "Adventure", emoji: "🧗" },
  { label: "Beaches", emoji: "🏖️" },
  { label: "Shopping", emoji: "🛍️" },
  { label: "Museums", emoji: "🏛️" },
  { label: "Nature", emoji: "🌿" },
  { label: "Nightlife", emoji: "🌃" },
  { label: "Culture", emoji: "🎭" },
  { label: "Wildlife", emoji: "🦁" },
  { label: "Photography", emoji: "📷" },
  { label: "Wellness", emoji: "🧘" },
  { label: "History", emoji: "🏰" },
] as const;

export const HOTEL_OPTIONS = [
  {
    value: "Budget",
    title: "Budget",
    description: "Hostels & guesthouses",
    price: "₹1–3k / night",
  },
  {
    value: "Mid-range",
    title: "Mid-range",
    description: "3–4★ hotels with comfort",
    price: "₹4–10k / night",
  },
  {
    value: "Luxury",
    title: "Luxury",
    description: "5★ resorts & suites",
    price: "₹15k+ / night",
  },
] as const;
